// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OficiosYa.Infrastructure.Persistence;

#nullable disable

namespace OficiosYa.Infrastructure.Migrations
{
    [DbContext(typeof(OficiosYaDbContext))]
    [Migration("20251118181548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OficiosYa.Domain.Entities.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCalificaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCalificadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioCalificaId");

                    b.HasIndex("UsuarioCalificadoId");

                    b.ToTable("Calificaciones", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.DireccionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DireccionesUsuario", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Oficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("IconoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Oficios", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.SolicitudCandidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanciaCliente")
                        .HasColumnType("double precision");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoEstimadoLlegada")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("SolicitudesCandidatos");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.SolicitudServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<int>("OficioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecioFinal")
                        .HasColumnType("numeric");

                    b.Property<int?>("TrabajadorAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("OficioId");

                    b.HasIndex("TrabajadorAsignadoId");

                    b.ToTable("SolicitudesServicio", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<double>("RatingPromedio")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalTrabajosRealizados")
                        .HasColumnType("integer");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Trabajadores", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.TrabajadorOficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnosExperiencia")
                        .HasColumnType("integer");

                    b.Property<string>("CertificadosUrl")
                        .HasColumnType("text");

                    b.Property<int>("OficioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioHoraBase")
                        .HasColumnType("numeric");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OficioId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("TrabajadoresOficios", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.UbicacionTrabajador", b =>
                {
                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrabajadorId");

                    b.ToTable("UbicacionesTrabajadores", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.SolicitudServicio", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "UsuarioCalifica")
                        .WithMany()
                        .HasForeignKey("UsuarioCalificaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "UsuarioCalificado")
                        .WithMany()
                        .HasForeignKey("UsuarioCalificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioCalifica");

                    b.Navigation("UsuarioCalificado");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.DireccionUsuario", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.SolicitudCandidato", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.SolicitudServicio", "Solicitud")
                        .WithMany("Candidatos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.SolicitudServicio", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.DireccionUsuario", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Oficio", "Oficio")
                        .WithMany()
                        .HasForeignKey("OficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Trabajador", "TrabajadorAsignado")
                        .WithMany()
                        .HasForeignKey("TrabajadorAsignadoId");

                    b.Navigation("Cliente");

                    b.Navigation("Direccion");

                    b.Navigation("Oficio");

                    b.Navigation("TrabajadorAsignado");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Trabajador", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("OficiosYa.Domain.Entities.Trabajador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.TrabajadorOficio", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Oficio", "Oficio")
                        .WithMany("Trabajadores")
                        .HasForeignKey("OficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficiosYa.Domain.Entities.Trabajador", "Trabajador")
                        .WithMany("Oficios")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficio");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.UbicacionTrabajador", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Trabajador", "Trabajador")
                        .WithOne("Ubicacion")
                        .HasForeignKey("OficiosYa.Domain.Entities.UbicacionTrabajador", "TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("OficiosYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Oficio", b =>
                {
                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.SolicitudServicio", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Trabajador", b =>
                {
                    b.Navigation("Oficios");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("OficiosYa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
